# theme: jekyll-theme-cayman
title: Mathieu Perton
#description: 

highlighter: rouge
plugins:
  - jemoji
##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true

exclude: ['README.md']
