# Setup
title:        Zack Spica
tagline:      Pro website
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Zack Spica
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
